<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findQuestions()
    {

        $query = $this->createQueryBuilder('q');
        return $query->select('q')
            ->where('q.questiontext is not null')
            ->getQuery()
            ->getResult();
    }
}
